apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid
  labels:
    app: bid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bid
  template:
    metadata:
      labels:
        app: bid
    spec:
      containers:
        - name: bid
          image: username/bid:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5